= Deploy and Scale a Simple App

== Goal

Deploy a simple PHP app, scale it, check its logs and SSH into a container.

Approximate time: 15 minutes

== Exercises

=== Push a simple PHP app

. In the cf CLI, make sure you are targeting your PWS installation and development space.

. In the cf CLI, verify that PWS includes a PHP buildpack (use cf help if needed).

. In your home directory on your computer, create a php-app-<your initials and a random number> directory. The name must be unique when deploying the app to PWS.

. Inside of that new directory, create an index.php file as follows (copy and paste the text below into the file):

....
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Hello world</title>
    </head>
    <body>
          <p>Hello world<?php echo " version 1"; ?></p>
    </body>
</html>
....

[start=5]

. In a terminal window, *change to the directory containing your index.php file*. Run `cf push` to deploy the application. Use the same application name as the directory created earlier: php-app-<your initials and a random number>.

. Use the cf CLI to verify that your app is now in the development space.

. View the app in PWS's Apps Manager.

. View the execution of the app in a browser (the link is in Apps Manager).

=== Scale the app

. Using Apps Manager, increase the number of instances for you app to 2. Notice how quick this is, since the droplet just needs to be copied to a new container.

. Using the cf CLI, decrease the number of instances for your app back to 1.

=== View logs and events for the app

. In Apps Manager, select your application and view the logs and events.

. Using the cf CLI, tail the logs for your app (due to company firewall restrictions, this
may not work - if not, you can also tail logs using the Apps Manager)

. Refresh your browser for the app to generate a log entry. Use CTRL-C to stop the tailing.

=== SSH into a Container

. (This exercise assumes that you are on an environment that has enabled SSH container access, such as PWS.) Use the cf CLI to access the first instance
of your application's container. `cf ssh <app name>`. Browse the container. Type `exit` to exit the SSH session.

Congratulations, you have pushed an application, scaled it, viewed its logs and SSH'd into a container.
