Vagrant.configure('2') do |config|

    config.vm.define "boshlite" do |boshlite|
		boshlite.vm.box = 'cloudfoundry/bosh-lite'

		boshlite.vm.provider :virtualbox do |v, override|
			override.vm.box_version = '9000.130.0'
			override.vm.network :private_network, ip: '192.168.50.4', id: :local
		end

		boshlite.vm.provider "virtualbox" do |v|
			v.memory = 6192
			v.cpus = 2
		end
    end

    config.vm.define "jumpbox" do |jumpbox|
    	jumpbox.vm.box = "ubuntu/trusty64"

		jumpbox.vm.provider :virtualbox do |v, override|
			override.vm.network :private_network, ip: '192.168.50.5', id: :local
		end

		jumpbox.vm.provider "virtualbox" do |v|
			v.memory = 1024
			v.cpus = 1
		end
    end
end
